# Generated by Django 5.2.3 on 2025-07-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
        ('university_programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityStudents',
            fields=[
                ('university_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprogramdurations')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.faculties')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'university_students',
                'managed': True,
            },
        ),
    ]
