# Generated by Django 5.2.3 on 2025-07-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
        ('universities', '0001_initial'),
        ('university_programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreUniversityCourses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pre_university_courses',
            },
        ),
        migrations.CreateModel(
            name='PreUniTutors',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise_area', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_students.preuniversitycourses')),
            ],
            options={
                'db_table': 'pre_uni_tutors',
            },
        ),
        migrations.CreateModel(
            name='PreUniParticipants',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('completion_status', models.CharField(blank=True, max_length=15, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('post_al_student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.postalstudents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_students.preuniversitycourses')),
            ],
            options={
                'db_table': 'pre_uni_participants',
            },
        ),
        migrations.CreateModel(
            name='UniversityStudents',
            fields=[
                ('uni_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('current_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('graduation_status', models.CharField(blank=True, max_length=15, null=True)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
                ('post_al_student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.postalstudents')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'university_students',
            },
        ),
    ]
