# Generated by Django 5.2.3 on 2025-08-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityStudentEducation',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('gpa', models.CharField(blank=True, max_length=10, null=True)),
                ('university_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='university_students.universitystudents')),
            ],
            options={
                'db_table': 'university_student_education',
            },
        ),
        migrations.CreateModel(
            name='UniversityStudentExperience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('university_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='university_students.universitystudents')),
            ],
            options={
                'db_table': 'university_student_experience',
            },
        ),
        migrations.CreateModel(
            name='UniversityStudentSocialLinks',
            fields=[
                ('social_links_id', models.AutoField(primary_key=True, serialize=False)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('x', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('university_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='university_students.universitystudents')),
            ],
            options={
                'db_table': 'university_student_social_links',
            },
        ),
    ]
