# Generated by Django 5.2.3 on 2025-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicresource',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicresource',
            name='related_course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicresource',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
