export const COUNSELLOR_MOCKS = [
  {
    id: 1,
    fullName: 'Anushka Fernando',
    email: 'anushka.fernando@uniroute.lk',
    phone: '+94 77 123 4567',
    location: 'Colombo, Western Province',
    languages: ['English', 'Sinhala'],
    specializations: ['STEM Pathways', 'Scholarship Guidance', 'Interview Coaching'],
    studentsSupported: 132,
    sessionsCompleted: 348,
    averageRating: 4.9,
    responseTime: '1h 40m',
    status: 'active',
    verified: true,
    joinedDate: '2023-02-18',
    lastActive: '2025-10-18T09:20:00Z',
    experienceYears: 9,
    education: 'MSc in Career Counseling, University of Colombo',
    certifications: ['NCDA Certified Career Counselor', 'British Council Education Advisor'],
    bio: 'Licensed career counsellor specializing in STEM pathways, international scholarships and readiness coaching for competitive university applications.'
  },
  {
    id: 2,
    fullName: 'Dinuka Jayasinghe',
    email: 'dinuka.jayasinghe@uniroute.lk',
    phone: '+94 76 221 8899',
    location: 'Kandy, Central Province',
    languages: ['English', 'Sinhala', 'Tamil'],
    specializations: ['Humanities Pathways', 'Aptitude Assessments', 'Leadership Development'],
    studentsSupported: 98,
    sessionsCompleted: 244,
    averageRating: 4.7,
    responseTime: '2h 10m',
    status: 'active',
    verified: true,
    joinedDate: '2023-06-09',
    lastActive: '2025-10-19T15:05:00Z',
    experienceYears: 7,
    education: 'BA in Psychology, University of Peradeniya',
    certifications: ['Career Guidance Practitioner (TVEC)', 'Youth Leadership Facilitator'],
    bio: 'Passionate about guiding students in humanities and social sciences with a focus on leadership and personal development.'
  },
  {
    id: 3,
    fullName: 'Harini Weerasinghe',
    email: 'harini.weerasinghe@uniroute.lk',
    phone: '+94 74 665 3210',
    location: 'Galle, Southern Province',
    languages: ['English', 'Sinhala'],
    specializations: ['Medicine Admissions', 'Personal Statements', 'Interview Preparation'],
    studentsSupported: 156,
    sessionsCompleted: 402,
    averageRating: 4.95,
    responseTime: '58m',
    status: 'active',
    verified: true,
    joinedDate: '2022-11-22',
    lastActive: '2025-10-20T08:10:00Z',
    experienceYears: 11,
    education: 'MBBS, University of Sri Jayewardenepura',
    certifications: ['Certified Guidance Counsellor (NIE)', 'Cambridge Admissions Advisor'],
    bio: 'Former medical admissions advisor helping students craft compelling applications for medical schools world-wide.'
  },
  {
    id: 4,
    fullName: 'Imasha Perera',
    email: 'imasha.perera@uniroute.lk',
    phone: '+94 77 908 4532',
    location: 'Negombo, Western Province',
    languages: ['English', 'Sinhala'],
    specializations: ['Financial Aid Planning', 'Vocational Pathways', 'Work-Study Balance'],
    studentsSupported: 74,
    sessionsCompleted: 165,
    averageRating: 4.4,
    responseTime: '3h 05m',
    status: 'inactive',
    verified: false,
    joinedDate: '2024-03-04',
    lastActive: '2025-09-27T13:30:00Z',
    experienceYears: 5,
    education: 'BCom in Finance, University of Kelaniya',
    certifications: ['Financial Guidance Specialist'],
    bio: 'Supports students in designing affordable education plans and alternative vocational tracks aligned to personal goals.'
  },
  {
    id: 5,
    fullName: 'Ramesh Balasuriya',
    email: 'ramesh.balasuriya@uniroute.lk',
    phone: '+94 75 554 7820',
    location: 'Jaffna, Northern Province',
    languages: ['English', 'Tamil'],
    specializations: ['Overseas Admissions', 'STEM Pathways', 'IELTS Preparation'],
    studentsSupported: 121,
    sessionsCompleted: 298,
    averageRating: 4.6,
    responseTime: '1h 55m',
    status: 'active',
    verified: false,
    joinedDate: '2023-08-16',
    lastActive: '2025-10-18T19:45:00Z',
    experienceYears: 8,
    education: 'BEng in Electrical Engineering, University of Ruhuna',
    certifications: ['British Council IELTS Coach'],
    bio: 'Helps northern province students access scholarships and international pathways in engineering and technology.'
  },
  {
    id: 6,
    fullName: 'Sajani Abeykoon',
    email: 'sajani.abeykoon@uniroute.lk',
    phone: '+94 76 872 1900',
    location: 'Matara, Southern Province',
    languages: ['English', 'Sinhala'],
    specializations: ['Creative Arts Pathways', 'Portfolio Building', 'Gap Year Planning'],
    studentsSupported: 63,
    sessionsCompleted: 142,
    averageRating: 4.5,
    responseTime: '2h 35m',
    status: 'inactive',
    verified: true,
    joinedDate: '2024-01-12',
    lastActive: '2025-09-02T17:05:00Z',
    experienceYears: 6,
    education: 'BA in Fine Arts, University of Visual & Performing Arts',
    certifications: ['Creative Career Coach'],
    bio: 'Guides creative students through portfolio development, international art school admissions and gap year planning.'
  }
];
