# Generated by Django 5.2.3 on 2025-10-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreUniversityCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('engineering', 'Engineering'), ('programming', 'Programming'), ('business', 'Business'), ('other', 'Other')], max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('thumbnail_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='LKR', max_length=10)),
                ('is_paid_course', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('enroll_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_courses', to='accounts.users')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='accounts.users')),
            ],
            options={
                'db_table': 'pre_university_courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('video_url', models.URLField()),
                ('video_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_provider', models.CharField(choices=[('cloudinary', 'Cloudinary'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='cloudinary', max_length=50)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_preview', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pre_university_courses.preuniversitycourse')),
            ],
            options={
                'db_table': 'course_videos',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.users')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pre_university_courses.preuniversitycourse')),
            ],
            options={
                'db_table': 'course_enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watched_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='pre_university_courses.courseenrollment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_university_courses.coursevideo')),
            ],
            options={
                'db_table': 'video_progress',
                'unique_together': {('enrollment', 'video')},
            },
        ),
    ]
