# Generated by Django 5.2.3 on 2025-10-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_alter_mentoringsessions_status_mentoravailability_and_more'),
        ('pre_university_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preuniversitycourse',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_courses', to='mentoring.mentors'),
        ),
        migrations.AlterField(
            model_name='preuniversitycourse',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='mentoring.mentors'),
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('ppt', 'Presentation'), ('excel', 'Spreadsheet'), ('image', 'Image'), ('zip', 'Archive'), ('link', 'External Link')], max_length=20)),
                ('file_url', models.URLField()),
                ('file_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='pre_university_courses.preuniversitycourse')),
            ],
            options={
                'db_table': 'course_resources',
                'ordering': ['course', 'order'],
            },
        ),
    ]
