# Generated by Django 5.2.3 on 2025-10-20 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pre_university_courses', '0002_alter_preuniversitycourse_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ratings', to='pre_university_courses.courseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ratings', to='accounts.users')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='pre_university_courses.coursevideo')),
            ],
            options={
                'db_table': 'video_ratings',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'video')},
            },
        ),
    ]
