# Generated by Django 5.2.3 on 2025-07-03 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universities',
            old_name='website_url',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='universities',
            old_name='contact_phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='universities',
            old_name='established_year',
            new_name='ugc_ranking',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='university_code',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='university_type',
        ),
        migrations.AddField(
            model_name='universities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 3, 1, 53, 39, 486379, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universities',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='universities',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 7, 3, 1, 53, 55, 726766, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universities',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
