# Generated by Django 5.2.3 on 2025-07-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_title', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='university_account', to='accounts.users')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_university_requests', to='accounts.users')),
            ],
            options={
                'db_table': 'university_requests',
                'ordering': ['-submitted_at'],
                'managed': True,
            },
        ),
    ]
