# Generated by Django 5.2.3 on 2025-10-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_universitydashboardadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDashboardA',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_subtitle', models.TextField(blank=True, null=True)),
                ('stats', models.JSONField(default=list)),
                ('quick_actions', models.JSONField(default=list)),
                ('recent_activities', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=list)),
                ('statuses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'university_dashboard_A',
                'managed': True,
            },
        ),
    ]
