# Generated by Django 5.2.3 on 2025-10-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_universitydashboarda'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityManagePortfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_info', models.JSONField(default=dict)),
                ('achievements', models.JSONField(default=list)),
                ('ranking_history', models.JSONField(default=list)),
                ('faculties', models.JSONField(default=list)),
                ('degree_programs', models.JSONField(default=list)),
                ('recent_events', models.JSONField(default=list)),
                ('facilities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'manage_portfolio',
                'managed': True,
            },
        ),
    ]
