# Generated by Django 5.2.3 on 2025-10-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_universitymanageportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAnnouncement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=150)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'university_announcement',
                'managed': True,
            },
        ),
    ]
