# Generated by Django 5.2.3 on 2025-07-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DegreePrograms',
            fields=[
                ('degree_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject_stream_required', models.CharField(blank=True, max_length=10, null=True)),
                ('career_paths', models.TextField(blank=True, null=True)),
                ('syllabus_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.universities')),
            ],
            options={
                'db_table': 'degree_programs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DegreeProgramDurations',
            fields=[
                ('duration_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_years', models.IntegerField()),
                ('degree_type', models.CharField(max_length=7)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
            ],
            options={
                'db_table': 'degree_program_durations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DegreeProgramCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('is_core', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.courses')),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
            ],
            options={
                'db_table': 'degree_program_courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DegreeProgramZScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('z_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
            ],
            options={
                'db_table': 'degree_program_z_scores',
                'managed': True,
            },
        ),
    ]
