# Generated by Django 5.2.3 on 2025-07-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_results', '0002_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='DegreePrograms',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('program_code', models.CharField(blank=True, max_length=20, null=True)),
                ('degree_type', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_years', models.IntegerField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.faculties')),
            ],
            options={
                'db_table': 'degree_programs',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgramDurations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration_type', models.CharField(blank=True, max_length=20, null=True)),
                ('duration_value', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
            ],
            options={
                'db_table': 'degree_program_durations',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgramCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_compulsory', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.courses')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
            ],
            options={
                'db_table': 'degree_program_courses',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgramZScores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('z_score_cutoff', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('district_rank_cutoff', models.IntegerField(blank=True, null=True)),
                ('island_rank_cutoff', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_results.subjectstreams')),
            ],
            options={
                'db_table': 'degree_program_z_scores',
            },
        ),
        migrations.CreateModel(
            name='FacultyDegreePrograms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.faculties')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_programs.degreeprograms')),
            ],
            options={
                'db_table': 'faculty_degree_programs',
            },
        ),
    ]
