# Generated by Django 5.2.3 on 2025-10-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_universityannouncement'),
        ('university_programs',
         '0002_academiccontent_facultydegreeprograms_subjectfile_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='degreeprograms',
                    name='faculty',
                    field=models.ForeignKey(blank=True, db_column='faculty_id', null=True,
                                            on_delete=django.db.models.deletion.DO_NOTHING, to='universities.faculties'),
                ),
            ],
            database_operations=[],
        )
    ]
