# Generated by Django 5.2.3 on 2025-11-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_programs', '0002_add_faculty_field'),
        ('university_programs', '0003_degreeprograms_faculty'),
    ]

    operations = [
    ]
