# Generated by Django 5.2.3 on 2025-11-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_merge_20251114_0230'),
        ('university_programs', '0004_merge_20251114_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeprograms',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='faculty_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universities.faculties'),
        ),
    ]
