# Generated by Django 5.2.3 on 2025-07-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reported_content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reported_content_id', models.IntegerField(blank=True, null=True)),
                ('report_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('report_status', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_action', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolved_reports', to='accounts.users')),
            ],
            options={
                'db_table': 'content_reports',
            },
        ),
    ]
