# Generated by Django 5.2.3 on 2025-10-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('university_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMentors',
            fields=[
                ('pre_mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('specializations', models.TextField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university_student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university_students.universitystudents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'pre_mentors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreMentorAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_mentors.prementors')),
            ],
            options={
                'db_table': 'pre_mentor_availability',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreMentorSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('session_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating_by_student', models.IntegerField(blank=True, null=True)),
                ('feedback_by_student', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pre_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_mentors.prementors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'pre_mentor_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreMentorEarnings',
            fields=[
                ('earning_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_date', models.DateField()),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_mentors.prementors')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pre_mentors.prementorsessions')),
            ],
            options={
                'db_table': 'pre_mentor_earnings',
                'managed': True,
            },
        ),
    ]
