# Generated by Django 5.2.3 on 2025-10-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_mentors', '0003_add_mentor_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prementors',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='prementors',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='prementors',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='prementors',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='prementors',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='prementors',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='prementors',
            name='total_sessions',
        ),
    ]
