# Generated by Django 5.2.3 on 2025-08-18 08:24

import apps.videos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("student_results", "0002_initial"),
        ("tutoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseVideo",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lecture", "Lecture"),
                            ("tutorial", "Tutorial"),
                            ("assignment_help", "Assignment Help"),
                            ("exam_prep", "Exam Preparation"),
                            ("lab_demo", "Lab Demonstration"),
                            ("project_guide", "Project Guide"),
                            ("other", "Other"),
                        ],
                        default="lecture",
                        max_length=20,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        help_text="Upload video file (MP4, AVI, MOV, WMV)",
                        upload_to=apps.videos.models.video_upload_path,
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Video thumbnail image",
                        null=True,
                        upload_to="videos/thumbnails/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_videos",
                        to="accounts.users",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject this video belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_results.alsubjects",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_videos",
                        to="tutoring.tutors",
                    ),
                ),
            ],
            options={
                "db_table": "course_videos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="videos.coursevideo",
                    ),
                ),
            ],
            options={
                "db_table": "playlist_videos",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="videos.videocomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.users"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="videos.coursevideo",
                    ),
                ),
            ],
            options={
                "db_table": "video_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoPlaylist",
            fields=[
                ("playlist_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to="tutoring.tutors",
                    ),
                ),
                (
                    "videos",
                    models.ManyToManyField(
                        related_name="playlists",
                        through="videos.PlaylistVideo",
                        to="videos.coursevideo",
                    ),
                ),
            ],
            options={
                "db_table": "video_playlists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="playlistvideo",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.videoplaylist"
            ),
        ),
        migrations.CreateModel(
            name="VideoView",
            fields=[
                ("view_id", models.AutoField(primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("watch_duration", models.DurationField(blank=True, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_views",
                        to="videos.coursevideo",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.users",
                    ),
                ),
            ],
            options={
                "db_table": "video_views",
            },
        ),
        migrations.AddIndex(
            model_name="coursevideo",
            index=models.Index(
                fields=["tutor", "status"], name="course_vide_tutor_i_0aff90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursevideo",
            index=models.Index(
                fields=["subject", "category"], name="course_vide_subject_685527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursevideo",
            index=models.Index(
                fields=["status", "is_public"], name="course_vide_status_ca4560_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlistvideo",
            unique_together={("playlist", "video")},
        ),
        migrations.AlterUniqueTogether(
            name="videoview",
            unique_together={("video", "viewer", "viewed_at")},
        ),
    ]
