# Generated by Django 5.2.3 on 2025-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.JSONField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoring_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MentoringSessionEnrollments',
            fields=[
                ('session_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoring_session_enrollments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MentoringSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentoring_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('approved', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentors',
                'managed': True,
            },
        ),
    ]
