# Generated by Django 5.2.3 on 2025-07-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('mentoring', '0001_initial'),
        ('students', '0001_initial'),
        ('university_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='mentoringsessionenrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
        migrations.AddField(
            model_name='mentoringsessionenrollments',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentoringsessions'),
        ),
        migrations.AddField(
            model_name='mentoringfeedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentoringsessions'),
        ),
        migrations.AddField(
            model_name='mentors',
            name='university_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university_students.universitystudents'),
        ),
        migrations.AddField(
            model_name='mentors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users'),
        ),
        migrations.AddField(
            model_name='mentoringsessions',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentors'),
        ),
    ]
