# Generated by Django 5.2.3 on 2025-10-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMentorApplications',
            fields=[
                ('pre_mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied', models.IntegerField(default=1)),
                ('form_data', models.JSONField(default=dict)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pre_apps', to='mentoring.mentors')),
            ],
            options={
                'db_table': 'pre_mentor_applications',
                'managed': True,
            },
        ),
    ]
