# Generated by Django 5.2.3 on 2025-07-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preferred_time', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=8)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=9)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentoring.mentors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
            ],
            options={
                'db_table': 'mentoring_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SessionDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentoring.mentoringrequests')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mentoring.mentoringsessions')),
            ],
            options={
                'db_table': 'session_details',
                'managed': True,
            },
        ),
    ]
