# Generated by Django 5.2.3 on 2025-08-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_mentoringrequests_sessiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringsessions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=9),
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='mentoring.mentors')),
            ],
            options={
                'db_table': 'mentor_availability',
                'managed': True,
                'unique_together': {('mentor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='MentorAvailabilityExceptions',
            fields=[
                ('exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('exception_type', models.CharField(choices=[('unavailable', 'Unavailable'), ('custom_available', 'Custom Available')], max_length=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='mentoring.mentors')),
            ],
            options={
                'db_table': 'mentor_availability_exceptions',
                'managed': True,
                'unique_together': {('mentor', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
