# Generated by Django 5.2.3 on 2025-10-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_alter_mentoringsessions_status_mentoravailability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='approved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
