# Generated by Django 5.2.3 on 2025-10-19 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0004_alter_mentoringsessions_status_mentoravailability_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallRoom',
            fields=[
                ('room_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_rooms', to='mentoring.mentors')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_rooms', to='mentoring.mentoringsessions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_rooms', to='students.students')),
            ],
            options={
                'db_table': 'video_call_rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoCallParticipant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('student', 'Student')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mentoring.videocallroom')),
            ],
            options={
                'db_table': 'video_call_participants',
                'managed': True,
                'unique_together': {('room', 'user_id', 'role')},
            },
        ),
    ]
