# Generated by Django 5.2.3 on 2025-10-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_videocallroom_videocallparticipant'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocallroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_rooms', to='students.students'),
        ),
    ]
