# Generated by Django 5.2.3 on 2025-10-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_alter_mentors_approved'),
        ('mentoring', '0006_alter_videocallroom_student'),
    ]

    operations = [
    ]
