# Generated by Django 5.2.3 on 2025-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0007_merge_20251019_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='approved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
