# Generated by Django 5.2.3 on 2025-11-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_prementorapplications'),
        ('mentoring', '0008_alter_mentors_approved'),
    ]

    operations = [
    ]
