# Generated by Django 5.2.3 on 2025-11-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0009_merge_20251114_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMentors',
            fields=[
                ('pre_mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('applied', models.IntegerField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pre_mentors',
                'managed': False,
            },
        ),
    ]
