# Generated by Django 5.2.3 on 2025-07-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('student_results', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_title', models.CharField(max_length=200)),
                ('session_description', models.TextField(blank=True, null=True)),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('session_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('session_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_results.alsubjects')),
            ],
            options={
                'db_table': 'tutoring_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionEnrollments',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=15, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutoringsessions')),
            ],
            options={
                'db_table': 'session_enrollments',
            },
        ),
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('availability_schedule', models.TextField(blank=True, null=True)),
                ('is_verified', models.IntegerField(blank=True, null=True)),
                ('rating_average', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_sessions_conducted', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'tutors',
            },
        ),
        migrations.CreateModel(
            name='TutorRatings',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('rating_date', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutoringsessions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutors')),
            ],
            options={
                'db_table': 'tutor_ratings',
            },
        ),
        migrations.AddField(
            model_name='tutoringsessions',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutors'),
        ),
        migrations.CreateModel(
            name='TutorFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutoringsessions')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutors')),
            ],
            options={
                'db_table': 'tutor_feedback',
            },
        ),
        migrations.CreateModel(
            name='TutorSubjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_results.alsubjects')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutors')),
            ],
            options={
                'db_table': 'tutor_subjects',
            },
        ),
    ]
