# Generated by Django 5.2.3 on 2025-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorfeedback',
            name='rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
