# Generated by Django 5.2.3 on 2025-10-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_tutoravailability_tutoringbooking'),
        ('tutoring', '0002_tutorfeedback_rating'),
    ]

    operations = [
    ]
