# Generated by Django 5.2.3 on 2025-10-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_merge_20251019_2253'),
        ('tutoring', '0003_merge_20251019_2338'),
    ]

    operations = [
    ]
