# Generated by Django 5.2.3 on 2025-10-19 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_merge_20251020_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text="Tutor's rate per hour in LKR", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
