# Generated by Django 5.2.3 on 2025-10-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_tutors_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TutoringSessionReschedule',
            fields=[
                ('reschedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_date', models.DateField(help_text='Original session date')),
                ('new_date', models.DateField(help_text='Rescheduled session date')),
                ('new_start_time', models.TimeField(help_text='Rescheduled start time')),
                ('new_end_time', models.TimeField(help_text='Rescheduled end time')),
                ('reason', models.TextField(blank=True, help_text='Reason for rescheduling', null=True)),
                ('requested_by', models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student')], help_text='Who requested the reschedule', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='tutoring.tutoringbooking')),
            ],
            options={
                'db_table': 'tutoring_session_reschedules',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
