# Generated by Django 5.2.3 on 2025-10-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_merge_20251019_1942'),
        ('tutoring', '0005_tutors_hourly_rate'),
    ]

    operations = [
    ]
