# Generated by Django 5.2.3 on 2025-10-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_merge_20251020_1601'),
        ('tutoring', '0006_merge_20251020_1837'),
    ]

    operations = [
    ]
