# Generated by Django 5.2.3 on 2025-10-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_alter_tutoringbooking_status_and_more'),
        ('tutoring', '0007_merge_20251020_1954'),
    ]

    operations = [
    ]
