# Generated by Django 5.2.3 on 2025-07-02 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpaces',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=100)),
                ('space_description', models.TextField(blank=True, null=True)),
                ('space_location', models.CharField(blank=True, max_length=50, null=True)),
                ('space_size', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_spaces',
            },
        ),
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_title', models.CharField(max_length=200)),
                ('ad_description', models.TextField(blank=True, null=True)),
                ('ad_content', models.TextField(blank=True, null=True)),
                ('ad_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_type', models.CharField(blank=True, max_length=30, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companies')),
            ],
            options={
                'db_table': 'advertisements',
            },
        ),
        migrations.CreateModel(
            name='AdBookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_status', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=15, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisements.adspaces')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisements.advertisements')),
            ],
            options={
                'db_table': 'ad_bookings',
            },
        ),
    ]
