# Generated by Django 5.2.3 on 2025-07-03 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='userdetails',
            table_comment='User details table',
        ),
    ]
