# Generated by hand for tracking daily login activity

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField()),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_logins', to='accounts.users')),
            ],
            options={
                'db_table': 'user_daily_logins',
                'managed': True,
                'unique_together': {('user', 'login_date')},
            },
        ),
    ]
