# Generated by Django 5.2.3 on 2025-10-20 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "verification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("email", models.CharField(db_index=True, max_length=100)),
                ("otp", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            (
                                "uni_student_registration",
                                "University Student Registration",
                            )
                        ],
                        max_length=64,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_sent_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "email_verifications",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["email", "purpose"], name="email_verif_email_83a1c3_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "purpose"), name="unique_email_purpose"
                    )
                ],
            },
        ),
    ]
