# Generated by Django 5.2.3 on 2025-10-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification'),
        ('accounts', '0002_userdailylogin'),
    ]

    operations = [
    ]
