# Generated by Django 5.2.3 on 2025-07-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_companyrequests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyevents",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="companyevents",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="companyevents",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="companyevents",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="companyevents",
            name="is_virtual",
        ),
        migrations.RemoveField(
            model_name="companyevents",
            name="max_participants",
        ),
        migrations.RemoveField(
            model_name="companyevents",
            name="meeting_link",
        ),
        migrations.RemoveField(
            model_name="companyevents",
            name="registration_deadline",
        ),
        migrations.AlterField(
            model_name="companyevents",
            name="event_type",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
