# Generated by Django 5.2.3 on 2025-08-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDashboardEdit',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=255)),
                ('story_subtitle', models.TextField(blank=True, null=True)),
                ('story_section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('story_description', models.TextField(blank=True, null=True)),
                ('story_second_description', models.TextField(blank=True, null=True)),
                ('story_image', models.CharField(blank=True, max_length=255, null=True)),
                ('offers', models.JSONField(default=list)),
                ('team', models.JSONField(default=list)),
                ('testimonials', models.JSONField(default=list)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companies')),
            ],
            options={
                'db_table': 'company_dashboard_edit',
                'managed': True,
            },
        ),
    ]
