# Generated by Django 5.2.3 on 2025-08-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companydashboardedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydashboardedit',
            name='announcements',
            field=models.JSONField(default=list),
        ),
    ]
