# Generated by Django 5.2.3 on 2025-11-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyrequests'),
        ('companies', '0007_companyad'),
    ]

    operations = [
    ]
