# Generated by Django 5.2.3 on 2025-10-19 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellors',
            fields=[
                ('counsellor_id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.TextField(blank=True, help_text='Areas of expertise and specializations', null=True)),
                ('bio', models.TextField(blank=True, help_text='Professional biography and background', null=True)),
                ('experience_years', models.IntegerField(blank=True, help_text='Years of counselling experience', null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Educational qualifications and certifications', null=True)),
                ('specializations', models.TextField(blank=True, help_text='Specialized areas like career guidance, academic counselling, etc.', null=True)),
                ('available_for_sessions', models.BooleanField(default=True, help_text='Whether accepting new mentoring sessions')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for sessions', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'db_table': 'counsellors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellorAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='counsellors.counsellors')),
            ],
            options={
                'db_table': 'counsellor_availability',
                'managed': True,
                'unique_together': {('counsellor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
