# Generated by Django 5.2.3 on 2025-10-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncellingSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=9)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counsellors.counsellors')),
            ],
            options={
                'db_table': 'counselling_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellingFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.JSONField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counsellors.councellingsessions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
            ],
            options={
                'db_table': 'counselling_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellingRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preferred_time', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=8)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=9)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counsellors.counsellors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
            ],
            options={
                'db_table': 'counselling_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellingSessionDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counsellors.counsellingrequests')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='counsellors.councellingsessions')),
            ],
            options={
                'db_table': 'counselling_session_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellingSessionEnrollments',
            fields=[
                ('session_enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='counsellors.councellingsessions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
            ],
            options={
                'db_table': 'counselling_session_enrollments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellorAvailabilityExceptions',
            fields=[
                ('exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('exception_type', models.CharField(choices=[('unavailable', 'Unavailable'), ('custom_available', 'Custom Available')], max_length=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='counsellors.counsellors')),
            ],
            options={
                'db_table': 'counsellor_availability_exceptions',
                'managed': True,
                'unique_together': {('counsellor', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
