# Generated by Django 5.2.3 on 2025-10-20 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preferred_time', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=8)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=9)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_requests', to='counsellors.counsellors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_requests', to='students.students')),
            ],
            options={
                'db_table': 'counselling_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellingSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=9)),
                ('session_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=8)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='counsellors.counsellors')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counsellors.counsellingrequests')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='students.students')),
            ],
            options={
                'db_table': 'counselling_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CounsellingFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.JSONField(help_text='JSON object with rating criteria and scores')),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_feedback', to='counsellors.counsellors')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_feedback', to='students.students')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='counsellors.counsellingsessions')),
            ],
            options={
                'db_table': 'counselling_feedback',
                'managed': True,
            },
        ),
    ]
