# Generated by Django 5.2.3 on 2025-10-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.JSONField()),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'counselling_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CounsellingRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preferred_time', models.CharField(max_length=100)),
                ('session_type', models.CharField(max_length=8)),
                ('urgency', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=9)),
                ('requested_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'counselling_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CounsellingSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(max_length=9)),
                ('session_type', models.CharField(max_length=8)),
                ('meeting_link', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'counselling_sessions',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='counselloravailability',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='counsellors',
            options={'managed': False},
        ),
    ]
