# Generated by Django 5.2.3 on 2025-10-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0002_counsellingfeedback_counsellingrequests_and_more'),
        ('counsellors', '0002_counsellingrequests_counsellingsessions_and_more'),
    ]

    operations = [
    ]
