# Generated by Django 5.2.3 on 2025-10-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0003_merge_20251021_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counsellingfeedback',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='counsellingrequests',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='counsellingsessions',
            options={'managed': True},
        ),
    ]
