# Generated by Django 5.2.3 on 2025-11-13 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0004_alter_counsellingfeedback_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingfeedback',
            name='counsellor',
            field=models.ForeignKey(default=2011, on_delete=django.db.models.deletion.CASCADE, related_name='counselling_feedback', to='counsellors.counsellors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellingfeedback',
            name='session',
            field=models.OneToOneField(default=2011, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='counsellors.counsellingsessions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellingfeedback',
            name='student',
            field=models.ForeignKey(default=2011, on_delete=django.db.models.deletion.CASCADE, related_name='counselling_feedback', to='students.students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellingrequests',
            name='counsellor',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='counselling_requests', to='counsellors.counsellors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellingrequests',
            name='student',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='counselling_requests', to='students.students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellingsessions',
            name='counsellor',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='counsellors.counsellors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellingsessions',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counsellors.counsellingrequests'),
        ),
        migrations.AddField(
            model_name='counsellingsessions',
            name='student',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='counselling_sessions', to='students.students'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counsellingfeedback',
            name='rating',
            field=models.JSONField(help_text='JSON object with rating criteria and scores'),
        ),
        migrations.AlterField(
            model_name='counsellingfeedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='counsellingrequests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='counsellingrequests',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='counsellingrequests',
            name='session_type',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=8),
        ),
        migrations.AlterField(
            model_name='counsellingrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='counsellingrequests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='counsellingrequests',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='counsellingsessions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='counsellingsessions',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='counsellingsessions',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellingsessions',
            name='session_type',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=8),
        ),
        migrations.AlterField(
            model_name='counsellingsessions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='counsellingsessions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
