# Generated by Django 5.2.3 on 2025-11-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0005_counsellingfeedback_counsellor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselloravailability',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='counsellors',
            options={'managed': True},
        ),
    ]
