# Generated by Django 5.2.3 on 2025-11-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_emailverification_0002_userdailylogin'),
        ('counsellors', '0006_alter_counselloravailability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselloravailability',
            name='counsellor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='availability', to='counsellors.counsellors'),
        ),
        migrations.AlterField(
            model_name='counselloravailability',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='counselloravailability',
            name='day_of_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='counselloravailability',
            name='is_active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='counselloravailability',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='available_for_sessions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='specializations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='counsellors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='counsellor_profile', to='accounts.users'),
        ),
    ]
