# Generated by Django 5.2.3 on 2025-07-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('student_results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_stage', models.CharField(max_length=7)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlStudents',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='students.students')),
                ('al_year', models.IntegerField(blank=True, null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_results.subjectstreams')),
            ],
            options={
                'db_table': 'al_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostAlStudents',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='students.students')),
                ('al_year', models.IntegerField(blank=True, null=True)),
                ('z_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_results.subjectstreams')),
            ],
            options={
                'db_table': 'post_al_students',
                'managed': True,
            },
        ),
    ]
