# Generated by Django 5.2.3 on 2025-07-02 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('student_results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlStudents',
            fields=[
                ('al_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('al_year', models.IntegerField(blank=True, null=True)),
                ('al_index_number', models.CharField(blank=True, max_length=20, null=True)),
                ('z_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('district_rank', models.IntegerField(blank=True, null=True)),
                ('island_rank', models.IntegerField(blank=True, null=True)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_results.subjectstreams')),
            ],
            options={
                'db_table': 'al_students',
            },
        ),
        migrations.CreateModel(
            name='PostAlStudents',
            fields=[
                ('post_al_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(blank=True, max_length=20, null=True)),
                ('gap_year_count', models.IntegerField(blank=True, null=True)),
                ('is_employed', models.IntegerField(blank=True, null=True)),
                ('employment_field', models.CharField(blank=True, max_length=100, null=True)),
                ('al_student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.alstudents')),
            ],
            options={
                'db_table': 'post_al_students',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('student_stage', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.users')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='OlStudentResults',
            fields=[
                ('ol_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=2)),
                ('ol_year', models.IntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_results.olsubjects')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students')),
            ],
            options={
                'db_table': 'ol_student_results',
            },
        ),
        migrations.AddField(
            model_name='alstudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.students'),
        ),
    ]
