# Generated by Django 5.2.3 on 2025-10-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('tutoring', '0003_merge_20251019_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringpayments',
            name='session',
        ),
        migrations.AddField(
            model_name='tutoringpayments',
            name='booking',
            field=models.ForeignKey(db_column='booking_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tutoring.tutoringbooking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringpayments',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutoringpayments',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tutoringpayments',
            name='card_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutoringpayments',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
