# Generated by Django 5.2.3 on 2025-11-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_merge_0003_companyrequests_0007_companyad'),
        ('payments', '0003_remove_tutoringpayments_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdPayments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companyad')),
            ],
            options={
                'db_table': 'company_ad_payments',
                'managed': True,
            },
        ),
    ]
