# Generated by Django 5.2.3 on 2025-10-20 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_set",
                        to="accounts.users",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocker_set",
                        to="accounts.users",
                    ),
                ),
            ],
            options={
                "db_table": "blocked_users",
                "managed": True,
                "unique_together": {("blocker", "blocked_user")},
            },
        ),
    ]
